### ISSUE TITLE
Refine Requirement: Visit links or barcodes

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#10]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

https://github.com/umgc/fall2022/issues/34 will help with this if completed, alternatively you can run the app on your own.

**Comment by kuku-prog** [comment]
User should get an offer  if they want to connect to the link or not.
User should have a option to choose between using the provided link or barcode to connect to(less likely both to appear together).

Q: This requirement works similar task as #9 for  each requirements give an option to connect to link, call that number or email the sender) wondering if this is a customer requirement question. If customer wants all sender information treated together or links/barcodes separate .
