### ISSUE TITLE
Refine Requirement: Look out for email from someone

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#12]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

https://github.com/umgc/fall2022/issues/34 will help with this if completed, alternatively you can run the app on your own.

**Comment by AliFahimi** [comment]
The user must have a way to add email addresses to a list that the application will use to notify users if an email came in from that address.
The user must have a way to delete email addresses from the list above.
The user must be notified when an email arrives from an email address in the listed email addresses (type of notification pending customer questions).

Additional requirements pending customer questions

**Comment by AliFahimi** [comment]
The user must have a way to add senders to a list that the application will use to notify users if any mail came in from that address.
The user must have a way to delete senders from the list above.
The user must be notified when mail arrives from a sender.
The notification must be a system notification
When the user selects a system notification, the application should open (if closed) and open the mail.
