### ISSUE TITLE
Write Deployment/Ops Guide Template

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#129]

**Comment by shaneknows** [comment]
It looks like Tatiana/Tramel set a lot of this up and broke the sections out so I filled in the one section that we didn't have a ticket for (Prepare Mobile Application for Use) a little and updated a bit of the intro as part of this ticket

**Comment by shaneknows** [comment]
Added missing section as ticket for next sprint that will depend on what new APIs we add and if we want to include instructions for the previous ones. I recommend ripping them from the previous cohort (at least the screenshots) if we do
