### ISSUE TITLE
Refine Requirement: Research cyclic consumer behavior to report to USPS and its customers 

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#13]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

https://github.com/umgc/fall2022/issues/34 will help with this if completed, alternatively you can run the app on your own.

**Comment by sHuber125** [comment]
I will help with this one.
