### ISSUE TITLE
Refine Requirement: Integrate with Google Assistant, Siri, Alexa

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#14]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

Consider highlighting potential redundancies/distinctions between #21, #14, #20, #15, #16

**Comment by AliFahimi** [comment]
Waiting on customer questions on if this is supposed to integrate with these assistants on the phone, or on devices such as a Google Home since they involve different requirements/work
