### ISSUE TITLE
Develop: Add "Back" gesture

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#144]
As a user on any page of the application other than "Home", I want to be able to swipe right from the left screen edge to go back to the previous page.

Acceptance Criteria
--
- User can swipe right from the edge of the screen to navigate back to the previous page they were on
- Action does nothing if on the homepage
- Action should not trigger navigation between emails, as that is a swipe right from within the display
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by JesterSe7en** [comment]
Using CupertinoPageRoute to create this feature for going back.  This will be applied for Android and iOS.

**Comment by mdconatser** [comment]
tested on android
