### ISSUE TITLE
Refine Requirement: Read for visually impaired (All features) 

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#16]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

Consider highlighting potential redundancies/distinctions between #21, #14, #20, #15, #16 

If there is already a good baseline for this in place within the application, consider benefits of potentially placing this requirement as a sub-requirement of each individual feature to be split amongst both teams instead of Team B taking this task across the board in order to reduce cross-team dependencies.

**Comment by Minyahil40** [comment]
Added a separate doc for review.
