### ISSUE TITLE
Refine Requirement: Search for a past email for a specified date range and sender

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#17]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

From Customer Meeting:
- Search Options should be on homepage for Date Range and Keyword (Search Sender/Body/Subject/etc)
- Option to default all mail to be From USPS Informed Delivery in the Settings (On/Off to check all mail)

**Comment by shaneknows** [comment]
Can enter Email Mode in application. Selecting Latest appears to return nothing no matter what, but Unread will show the first 30 Unread emails in your inbox. The contents displayed are Subject, Sender, Sent (time from now), and the body of the email if it can be parsed (Seems like there are some issues with this parsing as well).

Received this email, but none of the body could be processed:
![Image](https://user-images.githubusercontent.com/4079954/186921169-e51f9933-d69c-47ba-bc44-b38c1e4e18d4.png)


Application read "There is no content"
![Image](https://user-images.githubusercontent.com/4079954/186921282-f5f900a4-4933-4c82-8d5a-88f112f52be7.png)

**Comment by shaneknows** [comment]
Seems like adding some search options either to the home screen or list of emails would be pretty simple. Would recommend changing the date at the top to being a date range (defaulting to "empty"-"currentDate" to keep current functionality same) and then adding a sender option to enter text into before selecting the Lastest or Unread options to actually view the mail.


![Image](https://user-images.githubusercontent.com/4079954/186921595-e2ee4f51-49e2-461e-9309-f7342defa0df.png)
