### ISSUE TITLE
Refine Requirement: Store content of mailing cards to search in a user's storage (OCR search of images)

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#18]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

From Customer Meeting (8/28/22):
- Always have image stored, but for now storing the contents as plain text and displaying them as such for optimized lookups.

**Comment by shaneknows** [comment]
Google Vision API should allow us to rip the text from image. Would we like this to display as content when viewing a piece of mail? It seems like this functionality is currently not supported. Content is parsed and images appear to be skipped. We could add a new section for Image Contents or try to keep it inline with the text parsing
