### ISSUE TITLE
Update Cost Management Plan

### ISSUE THREAD

**Issue by cthorn2** [umgc/fall2022#181]

**Comment by kuku-prog** [comment]
I removed all the paragraph that was there. I did not know if I was supposed to update that writing or do something new.  I put some thing short with a table mainly based on the project charter. Please feel free to add or take stuff out. I still have the copy of the previous writing if there is an interest to put some points from it.

**Comment by mdconatser** [comment]
made comments

**Comment by jahanbbhat** [comment]
Reviewed, this can be closed.
