### ISSUE TITLE
Refine Requirement: Provide feedback to USPS on searches conducted providing marketing support 

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#19]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

From Customer Meeting (8/28/22):
- Record search terms as one record
- Record list of MID ID/Serial number (from envelope) of a search result as separate record
- Not tracking user data so only send info on search in relation to email pieces

**Comment by shaneknows** [comment]
Just need to know what data they would like to collect. Could easily provide just the search query (date range + sender), but that doesn't seem entirely useful.
