### ISSUE TITLE
Refine Requirement: Chatbot to provide access to search engine

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#20]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

Consider highlighting potential redundancies/distinctions between #21, #14, #20, #15, #16 

If there is already a good baseline for this in place within the application, consider benefits of potentially placing this requirement as a sub-requirement of each individual feature to be split amongst both teams instead of Team B taking this task across the board in order to reduce cross-team dependencies.

**Comment by lwvantassel** [comment]
From the customer meeting:
o	Is the chatbot intended to be able to access all current and planned application functions? (changing user views, scanning, listing/adding/removing notifications, search, performing link actions within messages) 
	Yes 

o	Is this intended to perform any functions external to the app (ex. Open browser with search query or search a user’s device storage beyond what is being stored as a result of the OCR function)? 
	Only in-app
