### ISSUE TITLE
Refine Requirement: Chatbot available through app (maybe website)

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#21]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

#34 will help with this if completed, alternatively you can run the app on your own.

Consider highlighting potential redundancies/distinctions between #21, #14, #20, #15, #16.

If there is already a good baseline for this in place within the application, consider benefits of potentially placing this requirement as a sub-requirement of each individual feature to be split amongst both teams instead of Team B taking this task across the board in order to reduce cross-team dependencies.

**Comment by mdconatser** [comment]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

**Comment by lwvantassel** [comment]
From the customer meeting:
o	What kind of dialog would be most beneficial for the user? For example, notifications, suggestions for what to search, suggestions for what to set notifications for 
	How to search (guide searches) 
        •	“Do you want to broaden your search for just bills?” 
	Overview of in-app functions 
       •	“Are you trying to do X?”, continued 

o	What need does this feature address for the user? For example, is the intention of the chatbot to provide helpful tips and suggestions or should the chatbot be more of an assistant that answers questions (similar to a help guide)? 
	See above 

o	What is the target user persona for the chatbot feature? 
	Everyone, make sure it supports disabled users 

o	Is the chatbot intended to replace the current voice input/narrator feature? 
	Up to us to make it easiest for the user
