### ISSUE TITLE
Add description of project methodology somewhere

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#214]
See item 2 of Roy's Team A Project Plan Feedback.

Consider adding a section (or incorporate in an existing section) a brief description on the development methodology (Agile, Waterfall, other) that is planned to be used for the project.  Reference is made to a Srum Master role by title but the planned development methodology could be cited more prominently.

**Comment by cthorn2** [comment]
I copied the project methodology from the project charter.  Do you think we need more information?
