### ISSUE TITLE
Add description of project methodology somewhere Roy Feedback #7

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#219]
See item 2 of Roy's Team A Project Plan Feedback.

Consider adding a section (or incorporate in an existing section) a brief description on the development methodology (Agile, Waterfall, other) that is planned to be used for the project.  Reference is made to a Srum Master role by title but the planned development methodology could be cited more prominently.

**Comment by shaneknows** [comment]
Added to 1.5
