### ISSUE TITLE
Incorporate miscellaneous Roy feedback # 1-3, 5,12

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#222]
Acronyms. Suggest a “hard Scrub” on acronyms and always “spell out” on first use. A very quick read identified a number of acronyms not yet included in section 1.5. (GFE, SDLC, CPARS, WBS, CI/CD, MID (Note I believe this is a postal acronym for “Mailer Identification number,” SOW, Q/A, and UMGC and ITEC (note the last two may not be recognized by a contract support team after hand of to the Postal Service. 

GFE - government furnished equipment 

SDLC - Software Development Life Cycle 

CPARS – Contractor Performance Assessment Reporting System 

WBS – Work Breakdown Structure 

MID - Mailer Identification number 

CI - Continuous Integration (CI)  

CD - Continuous Delivery (CD) 

SOW – statement of work 

QA – Quality Assurance 

UMGC – University of Maryland Global Campus 

SWEN - Software Engineering Project (SWEN) 

Misc. 

Section 1 – Project Information – first sentence currently reads “United States Post Office (USPS)…  Should read “United States Postal Service (USPS) 

Section 1.2 Purpose – second paragraph, last sentence reads: “The PMP will be revisited for possible revision or updates when any of the following condition occur:” I assume a list of conditions will be added. 

Section 1.4 Stakeholders. Please change my (Roy Gordon) email address to [USPSrgordon@aol.com](mailto:USPSrgordon@aol.com) 

Section 2.1 Scope. Misspelled word in third paragraph “Vale”

**Comment by shaneknows** [comment]
Section 1 – Project Information – first sentence currently reads “United States Post Office (USPS)… Should read “United States Postal Service (USPS)

_Updated_

Section 1.2 Purpose – second paragraph, last sentence reads: “The PMP will be revisited for possible revision or updates when any of the following condition occur:” I assume a list of conditions will be added.

_List was already there. Not sure if he just didn't see it or it printed weird_

Section 1.4 Stakeholders. Please change my (Roy Gordon) email address to [USPSrgordon@aol.com](mailto:USPSrgordon@aol.com)

_done_

Section 2.1 Scope. Misspelled word in third paragraph “Vale
_I don't see this_

**Comment by wpbear1742** [comment]
Add Team B Misc items

1.	Consider adding a “Documentation Information” table to page 2. Include: Document ID, Document Owner, Issue Date, Last Date Document Saved, File Name.


2. Suggest removing Approval Signatures for Robert Dixon, Dr. Mir Assadullah, and Roy Gordon.


3. Suggest removing Section 1.1 Purpose, second paragraph, first sentence: “Information provided in this PMP is determined from the Statement of Work (SOW) to be provided by the selected contractor……….”  I’m not familiar with a commitment to provide an SOW artifact and OCIO policies do not need to be cited.


5. 	Acronyms. Suggest a “hard Scrub” on acronyms and always “spell out” on first use. A very quick read identified a number of acronyms not yet included in Appendix A. (e.g. IDMA, OCR, HRHS) Also, it appears that Appendix A – Acronyms contains acronyms that do not appear in the document. (e.g. BAD, NFR, and others)


12.	Misc.
a.	Section 1.4, Table 1.1. Please change my (Roy Gordon) email address to [USPSrgordon@aol.com](mailto:USPSrgordon@aol.com)
b.	Section 3.5 first sentence.  Reference made to “Table XXXX.”
c.	Section 8 Risk Management, Figure x-0.  Recommend citing source of diagram if not original art.

**Comment by wpbear1742** [comment]
Add Team B Misc items

Consider adding a “Documentation Information” table to page 2. Include: Document ID, Document Owner, Issue Date, Last Date Document Saved, File Name. - Done

Suggest removing Approval Signatures for Robert Dixon, Dr. Mir Assadullah, and Roy Gordon. - Done

Suggest removing Section 1.1 Purpose, second paragraph, first sentence: “Information provided in this PMP is determined from the Statement of Work (SOW) to be provided by the selected contractor……….” I’m not familiar with a commitment to provide an SOW artifact and OCIO policies do not need to be cited. - Done

Acronyms. Suggest a “hard Scrub” on acronyms and always “spell out” on first use. A very quick read identified a number of acronyms not yet included in Appendix A. (e.g. IDMA, OCR, HRHS) Also, it appears that Appendix A – Acronyms contains acronyms that do not appear in the document. (e.g. BAD, NFR, and others) - Done

Misc.
a. Section 1.4, Table 1.1. Please change my (Roy Gordon) email address to [USPSrgordon@aol.com](mailto:USPSrgordon@aol.com) - Already Done
b. Section 3.5 first sentence. Reference made to “Table XXXX.” - Done
c. Section 8 Risk Management, Figure x-0. Recommend citing source of diagram if not original art. - Done
