### ISSUE TITLE
Fix digest view error

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#228]
Using the "Digest View" button on the application just ends up producing a non-informative error message.

**Comment by inoah1** [comment]
Created PR https://github.com/umgc/fall2022/pull/319 to resolve this issue

**Comment by inoah1** [comment]
Also, while reviewing this issue, I noticed another error that was occurring due to an inactive/expired service account being used by the google cloud vision plugin. Not sure if this is already being addressed but it will require us to setup a new service account and enable google cloud vision api.

**Comment by JesterSe7en** [comment]
Check https://github.com/umgc/fall2022/issues/193#issuecomment-1239977247 if you want to setup your own service account.

You will need to create your own if you want to try this.
