### ISSUE TITLE
Create mockup of a more usable and aesthetically pleasing mail view

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#234]
The customer has a strong desire for a better overall layout of the application. Mockups are the most effective way to demonstrate our ideas. Please include mockups as an attachment to this issue and the team can provide feedback, after which the SRS can be updated with new mockups.

**Comment by cthorn2** [comment]
Here is an example of an actual message from Informed Delivery along with a potential email view for the app.  It would be great if we could use text size to limit what information is pulled or at least what is prioritized into the email message.  That way, we could eliminate the fine print from mailers like the one shown here from showing up in the actual text email message that could eventually be read to the user.

Original Informed Delivery message
![Image](https://user-images.githubusercontent.com/111912838/189460686-a957931d-3898-43cb-8f94-7b468ed0a417.png)

Mobile formatted message - showing header and footer
![Image](https://user-images.githubusercontent.com/111912838/189460730-ccacad93-c14b-4ee2-9fea-4cacb21c8c66.jpg)

Mobile formatted message - showing side to side navigation
![Image](https://user-images.githubusercontent.com/111912838/189461525-192d57d2-db66-4156-ad77-9a658e70600e.png)

**Comment by cthorn2** [comment]
Another thought that might increase the value of the mail view might be to add a custom option to the text select actions menu that adds an a keyword alert for the selected word.  (https://stackoverflow.com/questions/62717516/creating-custom-text-selection-actions-in-a-flutter-app

![Image](https://user-images.githubusercontent.com/111912838/189488768-d268372a-96fb-4a33-98c4-d4a83fd72719.png)

)

**Comment by mdconatser** [comment]
- the contextual text selection actions would be pretty cool if it's automatic or we have time. 
- For the email view, I think it's probably important to still show the actual image by default, as well as repeating every single bit of text (even small print) below. Users who aren't mostly visually impaired will still want to see the image as it is likely laid out better than our text can be. Users who cannot see will need every bit of OCR text but can ignore the image.
- Could have settings to disable OCR/image output altogether
- I think we shouldn't try to "reformat" any of their message content -- might break if they change things and is less work for us. Inserting content before/after each mail image seems like it would be sufficient.
- can probably remove the left/right arrows and rely on gestures only, I don't think the icons are normally shown
- including the sender (if available), followed by email/phone/links before the OCR text would be hugely beneficial to help orient blind users

**Comment by cthorn2** [comment]
1. the contextual text selection actions would be pretty cool if it's automatic or we have time. 

_Yeah, it doesn't look that difficult once the functionality is already there._

2. For the email view, I think it's probably important to still show the actual image by default, as well as repeating every single bit of text (even small print) below. Users who aren't mostly visually impaired will still want to see the image as it is likely laid out better than our text can be. Users who cannot see will need every bit of OCR text but can ignore the image.   
 
_That is why I included the image as an attachment. Best practice has been moving toward limiting people from having to scroll down to see vital information.  Perhaps, if someone wants to see the image, maybe we give them a toggle (show image) in the settings.  I think the summer group was on track with their email windows, but they lacked tremendously in the formatting and recognizing of breaks <br> and paragraphs <p>  I am just wondering whether an executive summary would be better on a sales piece that a full text readout.  The difference is on a BGE or mortgage bill, you are not going to have the amount of text that you would on junk mail.  Is this where you are thinking about adding a setting to disabling OCR/image output?_  
 

6. I think we shouldn't try to "reformat" any of their message content -- might break if they change things and is less work for us. Inserting content before/after each mail image seems like it would be sufficient.

_I'm not sure I understand this comment?  Please elaborate?_

7. can probably remove the left/right arrows and rely on gestures only, I don't think the icons are normally shown

_I was thinking that the left/right images would be mostly transparent unless directly tapped by the user.  That way, you could still read the text, but we could remove that ugly rectangle from the bottom with the old navigation._

![Image](https://user-images.githubusercontent.com/111912838/189501579-d82063e9-7824-47a0-a7ff-4915f904ad0f.png)

_This is just an example and I don't like the way it overlays the text, but what about something like they do in hero sections on sites with the dots representing additional content._

![Image](https://user-images.githubusercontent.com/111912838/189501912-bbffe851-4e28-4a79-aebc-6d1d52957be2.png)

9. including the sender (if available), followed by email/phone/links before the OCR text would be hugely beneficial to help orient blind users

_Something like this for each scanned piece?_

![Image](https://user-images.githubusercontent.com/111912838/189503086-817f8917-e5f6-4c96-9ecc-d32db467f401.png)


_I'm trying to think of a way to logically break up the content.  The primary emails that we are focused on are coming from USPS Informed Delivery (ID), other email senders are secondary.  In the USPS ID email messages, you have N number are scanned mail images which can contain a phone number, email address or URL.  If you have five scanned mail pieces all with phone numbers, email addresses, and URLs, how do you want them displayed?  I think you would be right if the phone or email addresses are solely related to the email sender, but perhaps we need a split strategy._ 


![Image](https://user-images.githubusercontent.com/111912838/189503161-bcd3d823-a42c-4446-a538-3b9148fe1ad7.png)
