### ISSUE TITLE
Create mockup of a usable and aesthetically pleasing chatbot user interface

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#238]
The customer has a strong desire for a better overall layout of the application. Mockups are the most effective way to demonstrate our ideas. Please include mockups as an attachment to this issue and the team can provide feedback, after which the SRS can be updated with new mockups.

**Comment by shaneknows** [comment]
![Image](https://user-images.githubusercontent.com/4079954/189403309-1d0d02c2-d857-440d-b97c-91346e3602ca.png)

Updated main menu with nav item to open chat bot window

**Comment by shaneknows** [comment]
Actual chat window


![Image](https://user-images.githubusercontent.com/4079954/189407944-e303a11d-8555-47d3-a320-cb26b6dfbe55.png)

**Comment by mdconatser** [comment]
looks about right to me
