### ISSUE TITLE
Create mockup of a more usable and aesthetically pleasing Settings UI

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#241]
The customer has a strong desire for a better overall layout of the application. Mockups are the most effective way to demonstrate our ideas. Please include mockups as an attachment to this issue and the team can provide feedback, after which the SRS can be updated with new mockups.

**Comment by AndrewAsava** [comment]
![Image](https://user-images.githubusercontent.com/93182173/189554809-c76e714b-8ade-4f8c-be2d-0ffae3e3628a.png)

**Comment by AndrewAsava** [comment]
It's missing a few things that I wanted to include but here's what I have so far for review purposes for today. Tried to work off of what Shane had started for consistency's sake.
