### ISSUE TITLE
Create mockup of a usable and aesthetically pleasing search user interface

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#243]
The customer has a strong desire for a better overall layout of the application. Mockups are the most effective way to demonstrate our ideas. Please include mockups as an attachment to this issue and the team can provide feedback, after which the SRS can be updated with new mockups.

During the presentation, the idea of "search suggestions" based on what the user has entered so far was brought up, potentially with an AI library.

Replace home page

**Comment by shaneknows** [comment]
Updated main menu with dedicated search button: 

![Image](https://user-images.githubusercontent.com/4079954/189408181-40520657-d341-4e03-871a-7b864f073c5e.png)

**Comment by mdconatser** [comment]
- could use a bit of context/branding, maybe just replacing "Main Menu" in the header with logo/USPS

**Comment by shaneknows** [comment]
Simple search page.  Would add back button on the results to quickly go back to filters (same top menu and bottom menu bars). 

![Image](https://user-images.githubusercontent.com/4079954/189507806-1a3490f9-e3a4-4eda-ba4c-36fc34c5e16f.png)

**Comment by cthorn2** [comment]
I'm working across the teams on the UI initiative.  I have an idea for the main screen (home) that uses horizontal buttons instead of blocks so we can fill up the white space.  If we're going to rely on system accessibility functionality, do we still need the Microphone and headphone buttons on the interface?

![image](https://user-images.githubusercontent.com/111912838/189509161-b0e1545a-f5cc-4a4a-8664-42be0a983bbd.png)

**Comment by shaneknows** [comment]
The headphones are there to toggle the chatbot interface. And the microphone was just in case we did keep that functionality. Seemed worth having a few different takes on UI to present to the customer before digging in. I do like the key items on the bottom in your design, but I'm not a fan of the gradient color

**Comment by cthorn2** [comment]
Shane, thanks for the feedback.  I replaced the gradient and I agree that a solid color looks cleaner.  I also incorporated your chatbot UI into the design.

![image](https://user-images.githubusercontent.com/111912838/189536022-f6dc8219-3b33-44a9-83ec-b3f4ecfe05a9.png)
