### ISSUE TITLE
STP: Approach - Types of Testing Used

### ISSUE THREAD

**Issue by cthorn2** [umgc/fall2022#297]

**Comment by harsh2g** [comment]
@cthorn2 I think someone added information for this section last week? Please review.

**Comment by cthorn2** [comment]
Harsh, could you look at the last paragraph.  The entire section is coming back as 24% plagiarism with the following source being the having the largest impact on that number : https://www.atlassian.com/continuous-delivery/software-testing/types-of-software-testing.  In the introduction, I only referenced Unit, integration, and UAT.

**Comment by harsh2g** [comment]
@cthorn2 modified the last paragraph.

**Comment by cthorn2** [comment]
Great, thank you.
