### ISSUE TITLE
Add requirements to SRS to account for contacting email addresses/phone numbers that are not in your Contacts

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#302]

**Comment by cthorn2** [comment]
I believe this is already accounted for in the SRS under the following : 
3.1.19	Use Case Name: Call or text a phone number in an email or digest visually.
3.1.23	Use Case Name: Reply to an email address in an email or digest vocally.
3.1.22	Use Case Name: Send an email to an email address in an email or digest visually.
