### ISSUE TITLE
Scrub actual personal information (email address/phone) from SRS and Project Plan

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#312]
from professor: "Please scrub the email address because we are going to eventually publish this document and want to also protect the privacy of all individuals."

**Comment by shaneknows** [comment]
Is it not possible to delete the entire email address column? Looks like it would lose the Track Changes piece.

**Comment by tatikozh** [comment]
Yes, the Word won't track that change... I think it's ok to leave like that
