### ISSUE TITLE
Confirm and document Google Play App Store release process

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#315]
Need to figure out credentials and actual release process early so we know our timeline for submitting the app.

**Comment by shaneknows** [comment]
As soon as we can get owner permissions from the professor it should just be a matter of following the 'Enable the API' step here to get the application ID, adding that secret to the Secrets in GitHub, and uncommenting that pipeline step. This will setup the draft release from our CI/CD pipelines that we can then submit for review for the Google Play Store.

Source: https://developers.google.com/android-publisher/getting_started

**Comment by shaneknows** [comment]
Currently waiting identification approval for an account and then we should be able to test this

**Comment by shaneknows** [comment]
- Generate jks file for app signing via android studio

- set specified password in github secrets (current one is password so could just keep that and set KEYSTORE_PASS and KEYSTORE_KEY_PASS to password)

- Using pc-api credentials (provided by professor), set the SERVICE_ACCOUNT_JSON secret (to use in CI/CD pipeline)

- Upload aab in google play console or use github pipeline (recommended). NOTE: If there is a current draft in the play console, you may need to discard it and let the pipeline create a new one (this seems to be the case if the service account json changes)

-  Once the draft is in for internal testing a link can be sent out to testers or they can be added in the play console

**Comment by shaneknows** [comment]
Updated DevOps Guide 6.1: Deploying to the Google Play Store to outline this process
