### ISSUE TITLE
Project Plan: Cost Management

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#32]
Write

**Comment by Minyahil40** [comment]
added the cost management under the Cost Management section

**Comment by mdconatser** [comment]
include reference to the potential cost of google cloud vision subscription, license for Google Play store publishing, and license for iOS App Store publishing (out of scope for our project but noting cost for future iterations seems useful)

**Comment by shaneknows** [comment]
Looks good to me

**Comment by mdconatser** [comment]
added comments
