### ISSUE TITLE
TDD: Mail view considerations (phone/email/contacts)

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#340]
Ensure Mail view-related content for phone number, email, and contact features across the entire TDD (components, UIs, data structures, etc.) is completed and accurate.

**Comment by harsh2g** [comment]
I've reviewed the TDD and I do see some information related to phone number, email and contact. Is this ticket solely on reviewing and making sure the data is featured across the entire TDD or modifying the TDD too?
