### ISSUE TITLE
Ensure acronyms are spelled out on first use

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#354]
Investigate overall document, but at least address the following areas:

3. 4. 2.  TDD  - Miscellaneous comments regarding acronyms and "first use." 

Page 1, Section 1.2, first paragraph.  Suggest spelling out "QR" for first use. Did not see QR included in section 1.4 

Page 2, Section 1.4.  Check to make sure all acronyms identified are actually used in the document. 

Page 11, Section 6, first paragraph. Did not see GCP included in section 1.4

**Comment by cthorn2** [comment]
I've updated section 1.2 and working on 1.4.
