### ISSUE TITLE
Fix "Not to Be Tested" section

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#359]
From Roy:
Section 1.3.2, number 3 & 4 "Items Not to be Tested - the application shall run on the Android Operatng System / The application shall run on iOS.  Perhaps a notation on how risk associated with these two items are mitigated through testing activity on the intermediate layer?  

From Mike:
this section is confusing, we are definitely indirectly testing the application on both Android and iOS, and I'm not sure it's worth even specifying that we aren't testing flutter/dart.

**Comment by AliFahimi** [comment]
I added some things here, missed that you already grabbed it. Added some things according to Roys comment that it will be indirectly tested due to other test cases
