### ISSUE TITLE
Develop: Implement Google OAuth email retrieval

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#379]
As a user of the application, I want to be able to log in with any common email service.

Acceptance Criteria
--
- User has the option to log in to their Gmail account using OAuth
- User has the option to log in with the current username/password approach
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

Example of Apple's Mail login:
![Image](https://user-images.githubusercontent.com/3463782/190660289-41c4b2e1-f4c4-4a86-a750-fb6af06d80c4.png)

**Comment by mdconatser** [comment]
tested on android simulator, can't get it to work there but that may be expected without custom configuration on my end. I have an iPhone but no Mac, and I don't have an android device to try putting it on locally unfortunately.

**Comment by Minyahil40** [comment]
tested on iPhone. google login works fine

**Comment by tatikozh** [comment]
tested on iPad, the login works but no emails were retrieved.

**Comment by wpbear1742** [comment]
Tested on Android and Login does not work

Verified - iOS pass/ Android Fail
