### ISSUE TITLE
Develop: Modify home page structure to reflect mockup

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#381]
As a user of the application, I want the homepage to be laid out in a convenient way to access all features of the application.

Mockup: https://xd.adobe.com/view/db7cd80e-542d-495d-8909-01d4b2607dbe-8e2f/screen/ce00e410-1a79-4dd6-b4c8-471ba3261426/

Acceptance Criteria
--
- Homepage has a design that closely resembles the mockup
- Does not have to match styling, just the functional layout of it. Can use default style
- Buttons for existing features should still open that functionality
- Buttons for new features do not have to do anything
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by shaneknows** [comment]
Should probably attach mockup here

**Comment by AndrewAsava** [comment]
Chris in Team A pushed a home page design for review here in addition to other UI updates: https://github.com/umgc/fall2022/pull/487

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
