### ISSUE TITLE
Develop: Remove any settings related to old accessibility settings

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#382]
As a user of the application, I don't want it to include settings for functionality that doesn't exist.

Acceptance Criteria
--
- Any existing settings related to voice input or screen reader should be removed, since we are using native accessibility features instead.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")

**Comment by AndrewAsava** [comment]
https://github.com/umgc/fall2022/pull/490

Created a pull request (first time doing this, please let me know if I didn't do it right!) for updated settings files to be merged.

**Comment by AndrewAsava** [comment]
Since PR went through and was merged, going to go ahead and marked this as closed unless anyone has any objections/further comments.
