### ISSUE TITLE
Develop: Add OCR image caching to the email cache process

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#390]
As a user of the application, I want the search process to be fast, even for text found in images.

Acceptance Criteria
--
During the cache process developed by #385:
- All images per email need to be processed with Google Cloud Vision for OCR output 
- Resulting ImageText should be saved for each resulting MailPiece
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Update SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by shaneknows** [comment]
PR in where contents are fetched and stored in full text format. Work  has already been done to get all addresses in the mail, so future work can be done to get other contents or just dump the block of translated text.

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
