### ISSUE TITLE
Develop: Add Privacy Policy and Terms & Conditions view to login and settings

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#393]
As a user, I want the application to let me know its privacy policy and terms & conditions before using the application.

Acceptance Criteria
--
- Privacy Policy/Terms & Conditions are presented to user before allowing them to log in
- Content can be placeholder text and can be finalized in another Issue (#394)
- User must agree to these before logging in
- Privacy Policy/Terms & Conditions content can be re-viewed later on both the login screen and the settings page
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")

**Comment by AndrewAsava** [comment]
Link to PR here: https://github.com/umgc/fall2022/pull/542

Will need to jot down relevant thoughts/comments on process in Programmer guide

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
