### ISSUE TITLE
Develop: Add completed text content to Privacy Policy/Terms & Conditions

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#394]
This adds finalized text to the UI created in (#393) 

As a user, I want the privacy policy and terms and conditions to reflect the actual policies of the application.

Acceptance Criteria
--
- Privacy Policy/Terms & Conditions have finalized content to the best of our knowledge
- Content is written by us -- do not just reuse USPS since we are not affiliated and have different stances.
- Must reference what data we are storing and how we are using it

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
