### ISSUE TITLE
Develop: Add basic search input with date range

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#395]
As a user, I want to be able to navigate to a page for search.

See mockups: https://xd.adobe.com/view/db7cd80e-542d-495d-8909-01d4b2607dbe-8e2f/screen/82e4c1df-4679-457b-9096-2d932ceab552

Acceptance Criteria
--
- Search view is added to application
- Search view is accessible via homepage button
- Search view contains a textbox for keyword input
- Search view contains a date range filter
- Search view does not have to do anything, this is just to create the page
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by shaneknows** [comment]
branch: feature/243 has  some of the logic for this implemented, but may not follow the mockups closely

**Comment by tatikozh** [comment]
@shaneknows thank you! It did help a lot
