### ISSUE TITLE
Develop: Add ability to click on a search result to view the message

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#397]
Depends on #396 

As a user, I want to be able to click a mail piece in my search results to view it.

See mockups: https://xd.adobe.com/view/db7cd80e-542d-495d-8909-01d4b2607dbe-8e2f/screen/e421e377-e929-4977-bf38-eb51e5b9b2b3

Acceptance Criteria
--
- User can click an mail piece in the search results to navigate to the mail view
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
