### ISSUE TITLE
Develop: Implement search logic

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#398]
Light dependance on #395 (search page) and #396 (search results page), but can be worked alongside them.

As a user of the application, I want the keywords and date range I enter on the search page to search all of my mail pieces to provide a list of results.

Acceptance Criteria
--
- Search logic is added to application
  - Input: keyword string, start date, end date
  - Output: list of `MailPiece` objects
- All fields of the `MailPiece` object should be searched based on the keywords: Sender, ImageText
- Date range should apply to the `MailPiece` timestamp
- Search logic is called from the search page and is able to provide the results on the search results page
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
