### ISSUE TITLE
Develop: Create data object for MailPiece

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#400]
As a developer of the application, I need a `MailPiece` data object to work with so that all developers aren't putting in temporary workaround code.

Acceptance Criteria
--
The following models are added for developers to reference:
- `MailPiece` data object is available for developers to reference
  - ID (primary key)
  - EmailID (text) (some way to identify the email this MailPiece came from, so we can pull it again more easily from the server to get the image itself)
  - Timestamp
  - Sender
  - MID ID (text) (this is a field USPS adds to the mail piece images
  - ImageText (text)
- Object may be added to database setup if it has been configured, but not required for resolution of this story
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by SauterErin** [comment]
[EmailPiece.txt](https://github.com/umgc/fall2022/files/9639965/EmailPiece.txt)
