### ISSUE TITLE
Develop: Add typeahead support to search view

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#401]
As a user, I want to be able to start typing a keyword into the search input and have it automatically start to suggest matches under the search input. I want to be able to click on the matches to perform the search for it.

Acceptance Criteria
--
- Search input has typeahead support
- Typeahead suggestions can be clicked to perform the search
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Update SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by shaneknows** [comment]
Most functionality is there, just need to go to the mail view upon clicking an item

**Comment by Minyahil40** [comment]
Typehead functionality works as expected.

**Comment by mdconatser** [comment]
tested on android
