### ISSUE TITLE
Develop: Add search controls to search results view

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#402]
As a user, I want to be able to change my search query from the search results page.

Acceptance Criteria
--
- Search controls are available on the search results page.
  - Ideally, the same controls are reused rather than copied/pasted, could even combine the "search" page with the "results" page
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Update SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by shaneknows** [comment]
This may be tough as the current controls are quite large. Fixing the back button to actually go to the search page (currently goes home) may be minimum acceptable case for this. The current datepicker control requires selecting start and end date from the calendar so I doubt we will have the space unless we use some drawer type visual control.
