### ISSUE TITLE
Develop: Add logout capability

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#406]
As a user, I want to be able to log out of the application in case I need to switch email accounts or just sign out in general. This already exists within the application, but should be updated to function with the new login approach.

Acceptance Criteria
--
- Application contains a function to log out (via navigation or in settings)
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
if you log out and close the app, then reopen the app, it automatically logs me in again. i was logged in with a normal username/password, not google

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad
