### ISSUE TITLE
Develop: Add database for storing analytics data

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#409]
As a developer, I need a database structure set up that supports Google Analytics integration.

Also see #410 for overlap. To meet our needs, we may need two separate data storage techniques (or one if it meets all criteria of both stories).

Acceptance Criteria
--
- Database structure is set up within the application to support Google Analytics data
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by cthorn2** [comment]
I believe this will be all captured in Firebase, but more research will be needed.
