### ISSUE TITLE
Develop: Add database for storing application data

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#410]
As a developer, I need a database (or other data storage approach) set up within the application to store user data like settings, notifications, and email cache. Due to privacy concerns, this data should all reside within the user's own device and not sent to any cloud database storage that may be used by the analytics data.

Also see #409 for overlap. To meet our needs, we may need two separate data storage techniques (or one if it meets all criteria of both stories).

May need to use SqlCipher for encryption

Acceptance Criteria
--
- Data storage is configured for user data in the application
- Data storage is stored locally and not hosted in a cloud database.
- Should be in a format that performs well for search queries
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by cthorn2** [comment]
Flutter option for secure local storage - [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage)

If the platform is Android, then flutter_secure_storage stores data in [encryptedSharedPreference](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences), which are shared preferences that encrypt keys and values. It handles [AES encryption](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) to generate a secret key encrypted with [RSA](https://en.wikipedia.org/wiki/RSA_(cryptosystem)) and stored in [KeyStore](https://developer.android.com/reference/java/security/KeyStore).

For the iOS platform, flutter_secure_storage uses the [KeyChain](https://developer.apple.com/documentation/security/keychain_services) which is an iOS-specific secure storage used to store and access cryptographic keys only in your app.

Database options - 
1. [SQFlite with SQLCipher (Relational Database)](https://pub.dev/packages/sqflite_sqlcipher)
2. Realm (NoSQL) - offers a flexible solution; however, it will increase the size of the app download.
