### ISSUE TITLE
Develop: Add Google Analytics integration

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#411]
As an administrator of the application, I would like Google Analytics support to be added so that I can see an automated dashboard of various usage metrics.

Acceptance Criteria
--
- Google Analytics is fully configured with the application, and metrics can be seen on the Analytics webpage.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by cthorn2** [comment]
Still working on integrating Google Analytics further within the app, but I have limited analytics coming back at this point.  I live in Carney, MD  and it's able to pull that information in real-time on the emulator.  Tomorrow, I would like to see about capturing more information navigating within the app (screen views) and also capturing outbound links.

![Image](https://user-images.githubusercontent.com/111912838/191633515-8af5a470-cab3-4160-b86d-e9c51636d22f.png)

Reconfigured to add the new umgc.swen account information. 

[Google Analytics already tracks a default set of attributes.](https://support.demandbase.com/hc/en-us/articles/115000599003-Google-Analytics-Default-Attributes)

### **Firebase Instance Initialization**
//check to make sure the instance has been initialized, so multiple instances are not getting instantiated.

```
  if (Firebase.apps.length == 0) {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform,);
  }
```

### **UI Navigation**
// there are two options for setting the screenName attribute to monitor this change.
    
   `FirebaseAnalytics.instance.setCurrentScreen(screenName: "Main Menu");`

or 

```
    FirebaseAnalytics.instance.logEvent(
      name: 'screen_view',
      parameters: {
        'screenName': 'Main Menu',
        'screenClass': 'main_menu.dart',
      },
    );
```

### **Link Tracking**
// Need more information, right now links are striped from email messages.
Still researching

You should be able to log into Google Firebase or Analytics tomorrow afternoon/evening to see information from today.  It takes 24hours to update.

**Comment by cthorn2** [comment]
Pushed feature/411 to GitHub this afternoon.
