### ISSUE TITLE
Develop: Create Notification and NotificationSubscription data objects

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#412]
As a developer of the application, I need `Notification` and `NotificationSubscription` data objects to work with so that all developers aren't putting in temporary workaround code.

Acceptance Criteria
--
The following data objects are available for developers to reference:
- Add `Notification` object
  - Timestamp
  - EmailID (foreign key)
  - MID (individual mail piece ID)
  - NotificationSubscriptionKeyword (foreign key)
- Add `NotificationSubscription` object
  -  Keyword (string) (primary key to avoid duplicates)
- Objects are ideally added to the database unless it is not yet ready.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by harsh2g** [comment]
Completed.
