### ISSUE TITLE
Document App Store release concerns for Login

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#426]
As a developer, I need to know that our approach for Login will pass Apple and Google's guidelines for logins. For example, I know Apple has a policy that you must be able to "Log in with Apple" for apps that use other similar things like "Log in with Google". That may just be for account creations, while our situation is a little different. Pay attention to anything that might affect us for usernames/passwords as well. All findings should be documented here so that we have a better chance of resolving the issues before app store submission.

Acceptance Criteria
--
- Apple/Google app store guidelines for logging into user email accounts and utilizing usernames/passwords have been thoroughly evaluated for our purposes
- Findings and especially actions required is left as a comment on this Issue.

**Comment by Minyahil40** [comment]
**Social login service guidelines**

1. Apple for IOS Apps

Apps that use a third-party or social login service (such as Facebook Login, Google Sign-In, Sign in with Twitter, Sign In with LinkedIn, Login with Amazon, or WeChat Login) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option. A user’s primary account is the account they establish with your app for the purposes of identifying themselves, signing in, and accessing your features and associated services.
Sign in with Apple is not required if:

-	Your app exclusively uses your company’s own account setup and sign-in systems.
-	Your app is an education, enterprise, or business app that requires the user to sign in with an existing education or enterprise account.
-	Your app uses a government or industry-backed citizen identification system or electronic ID to authenticate users.
-	Your app is a client for a specific third-party service and users are required to sign in to their mail, social media, or other third-party account directly to access their content.

https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple




2. Google for Android Apps

There is no restriction to use social login service for android apps





**To Add Social Login Services using Auth0**

**Facebook**

- 	Require Facebook Developer Account
-	Need to create an app in Facebook developer portal( to generate App Id and App secret)

**Apple**

-	Require Apple Developer Program Account

**Microsoft**

-	Need to create an account on the Azure portal
-	Need to create an Azure AD Tenant
-	https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

**GitHub**

-	Need to Sign up for a GitHub Developer Account
-	https://github.com/settings/developers#oauth-apps

**LinkedIn**

-	Required to sign up for a LinkedIn Developer Account
-	https://www.linkedin.com/developers
-	Need to set up an up in LinkedIn Developer Portal
-	https://www.linkedin.com/developers/apps/new

**Discord**

-	Required to sign up for a Discord Developer Account
-	https://discord.com/developers
-	Need to set up an up in Discord Developer Portal
-	https://discord.com/developers/applications

**Comment by Minyahil40** [comment]
@mdconatser FYI
