### ISSUE TITLE
Document App Store guidelines for data storage

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#428]
As a developer, I need to know that we are meeting Apple/Google's guidelines for storing user data like emails and analytics data. This will make the submission process less of a risk of rejection.

Acceptance Criteria
--
- Consider encryption
- Apple/Google app store guidelines for storing user data (like emails and analytics data) is thoroughly evaluated for our specific plans
- Findings and especially actions required is left as comments in this Issue

**Comment by AliFahimi** [comment]
Apple:
We must have a privacy policy that says what data it collects and what it does with that data. Explain data retention policies (this would be more for our analytics)
We must request permission for any data collection even if data is anonymous. 
We should only request access to data we need
Technically if we do not have access to the data or it is not being sent off of the device we do not need to disclose it, but its better if we do.

Overall not much there on how we store it as long as we disclose it. We should keep best practices anyway (encryption etc)

Google:
We must be transparent on how we handle user data. Same as apple, privacy policy.
Data must be secure and there is a clear retention and deletion policy.

We will need to fill out a data safety form

Overall looks like Apple is more strict so we should follow that and it should cover what Google requires.
