### ISSUE TITLE
Implement Milestone 2 Feedback

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#446]
From review of documents by professor:
- Please fix the Table of Contents of STP
- STP 9.1.2 2, 9.2.2 1, 9.4.2 1, say that you are not testing prior functionality. Sometimes when we integrate work from elsewhere it may not work appropriately. We would still need to test that the work done by other still works in our code base.
- You can also indicate that you are not conducting any performance test.
- 9.4.3 Did Mr. Dixon say that he is going to provide test data?
- Please fix the Table of Contents of TDD
- Please make the architectural changes in TDD as discussed during the presentation.

From other feedback: 
- I noticed strategic strengths in one submission of STP as it had greater details in process and approach whereas greater strengths in the other STP where it has a number of test cases. The former team missed test cases and the latter was terse on approach and strategy. Please share your work with each other and learn from each others strengths to strengthen your weaknesses. Both teams, please submit updated STP next time.

**Comment by lwvantassel** [comment]
- removed previous functionality from items not tested
- performance testing is already listed under items not tested in section 9.3.2
- removed language stating that the customer would provide test data
-  updated unit tests to reflect implemented unit tests
