### ISSUE TITLE
Develop: Accessibility adjustments for Mail view

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#450]
As a user who enables accessibility features on my device, I want the application to be intuitive to use with these tools.

Acceptance Criteria
--
- For the Login Page:
  - All functionality can be read and interacted with using native screen reader tools
    - Controls are read in a logical order to orient the listener without looking at the screen
    - No extraneous content is read aloud which provides no value to the listener
  - All functionality can be accessed intuitively using native voice control tools
    - Controls can be accessed wherever possible using their "name" rather than forcing users to rely on "numbers"

**Comment by sims-007** [comment]
Test on Android complete

**Comment by wpbear1742** [comment]
Verified - Test PASS
