### ISSUE TITLE
Develop: Add functionality to perform searches with the chatbot

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#466]
As a user, I want to be able to use the chatbot to perform a date/keyword search.

Acceptance Criteria
--
- Chatbot can receive a request to search for a keyword, date range, or both.
- Chatbot can navigate the user to the search results page based on their input.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by shaneknows** [comment]
Currently have this loading the search page and populating filters in a branch, but need the results with search filter complete to implement this as the AC defines

**Comment by Minyahil40** [comment]
tested in IOS

**Comment by mdconatser** [comment]
tested on android

- can't seem to get the keyword to work from the chatbot, but it's possible I'm doing it wrong. I tried stuff like "search 10/23/2022 10/25/2022 subaru" and "search subaru" and neither worked
- I think the user would expect that this would also just submit the search to view a list of results, but we can keep it as-is at this point

**Comment by mdconatser** [comment]
i created a new bug specifically for those issues above

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Fail on Android

Separate Bug will be input.
