### ISSUE TITLE
Develop: Apply uniform style across application

### ISSUE THREAD

**Issue by cthorn2** [umgc/fall2022#477]
As a user, I want the application to have consistent navigation elements and style throughout the application.

Acceptance Criteria
--
- Across the pages the fall2022 cohort has added/refined so far (currently home, search, search results, chatbot), there should be a consistent navigation method and user interface styling.
  - This will set an example for future views added (notifications/management/login/mail view/settings)

**Comment by cthorn2** [comment]
Pushed branch [UI_Main_Menu](https://github.com/umgc/fall2022/tree/UI_Main_Menu) which includes an updated Main Menu page consistent with virtual walk-through and separate top_app_bar.dart file to standardize the appBar for all UI pages.  

call using the following code : set the title the title is dynamically pulled from the title value here.  Make sure you include the files top_app_bar.dart in your UI files.

`appBar: TopBar(title: "Main Menu"),`

**Comment by tatikozh** [comment]
@cthorn2 @mdconatser Just an idea for top and bottom bars. What do you guys think?

![Image](https://user-images.githubusercontent.com/35759841/193583503-dcdaa901-b88f-4925-8984-a3769b302111.png)



![Image](https://user-images.githubusercontent.com/35759841/193583524-1146693f-5a51-4730-b581-5674f0d7d024.png)

**Comment by cthorn2** [comment]
The updates look great.  I had looked at implementing the notch for the Chatbot but the home / main menu works well too.

**Comment by tatikozh** [comment]
@cthorn2 would you be ok if I'll push this update?
