### ISSUE TITLE
Develop: Clear all notifications

### ISSUE THREAD

**Issue by cthorn2** [umgc/fall2022#478]
As a user, I want a quick way to be able to clear all my current notifications at the same time.

Acceptance Criteria
--
- Button to clear all notifications is added to the notifications view.
- Upon being tapped, button clears all notifications.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
tested on android, entered a bug to fix recurring notifications
