### ISSUE TITLE
Determine if we can have a release pipeline

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#5]
Need to investigate if we can quickly set up a release pipeline to easily demonstrate our progress from the web. Create follow-on tasking to actually create the release pipeline with results of investigation

**Comment by shaneknows** [comment]
Pipeline may not be needed, but we can certainly release to the app stores from the CI/CD pipeline if we can acquire the developer licenses  ($25 Google/99 a year Apple). UMGC may have a license we can use as well.

Currently I have updated the build pipeline to generate the apks/aabs so we have a version of the software we could give in a zip folder to be run on Android devices

**Comment by shaneknows** [comment]
Putting this in review depending on customer decision of how they want the release handled

**Comment by shaneknows** [comment]
In customer meeting Bob Dixon said pipeline artifacts are sufficient ("however last team did it")
