### ISSUE TITLE
Save MailPieces created during cache process to the database

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#500]
As a developer, I want the `MailPiece` objects created during the cache process to be saved to the database.

Acceptance Criteria
--
- `MailPieces` created during the cache process are saved to the database.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
