### ISSUE TITLE
Expand OAuth login support

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#507]
As a potential user with an OAuth-capable email provider, I want to be able to log in to MailSpeak without providing the application itself my account's username and password.

Acceptance Criteria
--
- User can use OAuth login for Microsoft email account
- User can use OAuth login for Yahoo email account
- User can use OAuth login for Apple email account
- User can use OAuth login for Aol email account
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by Minyahil40** [comment]
on hold tasks
-  Apple ( need developer account )

- Microsoft ( app registration in Azure need more verification that require providing personal information)
