### ISSUE TITLE
Develop: Add advanced search

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#508]
As a user, I want to be able to search for mail from a specific sender without searching the full mail text.

Acceptance Criteria
--
- User can specifically search the "Sender" field with a search keyword
- User can specifically search the "ImageText" field with a search keyword
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
