### ISSUE TITLE
Develop: Add functionality to add notification subscription with the chatbot

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#519]
As a user, I want to be able to add a notification subscription using the chatbot.

Acceptance Criteria
--
- Chatbot accepts a command for adding a notification subscription with a keyword.
- Chatbot can add a notification subscription based on the input.
- Document any relevant content in the Programmer guide (draft thoughts of usage and importantly the "Why")
- Updates SRS and STP (and other docs if necessary)
- Add/Update relevant unit tests

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by lwvantassel** [comment]
tested on android virtual device

**Comment by wpbear1742** [comment]
Verified - Test PASS
