### ISSUE TITLE
Chatbot is missing bottom navigation bar

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#612]
As a user, I want the same bottom navigation bar no matter which page I'm on.

Acceptance Criteria
--
- Common bottom navigation bar is added to chatbot view

**Comment by Minyahil40** [comment]
tested in IOS

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
