### ISSUE TITLE
Improve user experience during cache process

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#613]
As a user, I don't want to just stare at a blank white screen for a while after I log in to the application. I want to either see a loading screen or just be able to use the application while it is refreshing data in the background.

Acceptance Criteria
--
- Cache process uses a loading screen or alternatively just does this process in the background (ideally with an indicator somewhere that data is still being downloaded)

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
