### ISSUE TITLE
Make date portion of the search optional

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#615]
As a user trying to search for an email by keyword across my whole history, I do not want to even select any kind of option for the dates. I would like to just enter my keyword and search, but right now I'm forced to manually scroll back in time to select a date range from then until today.

Acceptance Criteria
--
- By default, entering a keyword and selecting search will search across all dates.

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
