### ISSUE TITLE
Show less mail text in the search view

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#624]
As a user, I don't want the search view to contain the full text output of the mail. Just a few lines should suffice.

Acceptance Criteria
--
- Search view only displays at most a few lines of text plus an ellipsis (...) after the end. "Newlines" should be converted to spaces to fit more text sequentially in less vertical space.

**Comment by Minyahil40** [comment]
old view 
![Image](https://user-images.githubusercontent.com/111590407/197210709-f50c3969-12e6-48c4-9bff-2cf1973977c2.png)




new view
![Image](https://user-images.githubusercontent.com/111590407/197208430-a743c4b2-0cb8-4dc4-ade4-1be8c21a2340.png)

**Comment by mdconatser** [comment]
this was a good addition as well, but the original intent was for the "search results page". Also to convert newlines to spaces to fit more per line. 2 lines looks good on the "typeahead" that you did, but maybe expand it to 3 lines for the search results page.


![Image](https://user-images.githubusercontent.com/3463782/198066011-48d3abe2-6eaf-443c-b44e-92fcef3caca7.png)

**Comment by Minyahil40** [comment]
![Image](https://user-images.githubusercontent.com/111590407/198130325-e7383c2a-e6a8-426b-aca9-aa9ec66b2d35.png)
![Image](https://user-images.githubusercontent.com/111590407/198130327-831ec8d9-7c5d-434f-acf2-0f6758ceaca2.png)

**Comment by mdconatser** [comment]
tested on android
