### ISSUE TITLE
Mail view adjustments

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#628]
Acceptance Criteria
--
- Change "No photo loaded" text to "Loading image..." and ideally with a spinner icon

**Comment by cthorn2** [comment]
Andrew, I sent you a message in Teams, but I worked on some of this stuff in PR [#641](https://github.com/umgc/fall2022/pull/641)

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
