### ISSUE TITLE
Add remaining app features to the Chatbot

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#630]
Acceptance Criteria
--
- Digest view is accessible from chatbot
- Upload mail is accessible from chatbot
- Scan (take picture of) mail is accessible from chatbot

**Comment by shaneknows** [comment]
Digest view isn't quite updated yet

**Comment by Minyahil40** [comment]
tested in IOS. 

- digest command throws error
- upload command displays nothing

**Comment by mdconatser** [comment]
tested on android:

- All three commands work fine

**Comment by mdconatser** [comment]
@Minyahil40  @shaneknows  for easier understanding of where we stand, I split out the bugs you mentioned into a separate bug ticket

**Comment by Minyahil40** [comment]
tested on iPhone all works as expected

**Comment by tatikozh** [comment]
tested on iPad

**Comment by lwvantassel** [comment]
tested on android virtual device

**Comment by wpbear1742** [comment]
Verified - Test PASS
