### ISSUE TITLE
Typeahead not automatically visible

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#665]
As a user, I want to be able to see typeahead results as I type, instead of having to swipe up or close the keyboard.

Results should be visible upon typing instead of having to take a second action.

**Comment by shaneknows** [comment]
This is tough because of screen real estate. The keyboard is half the screen and then the textbox; doesn't leave much room

**Comment by mdconatser** [comment]
was thinking maybe if we could just auto scroll the screen up a bit when
clicking into the text field, it’d be enough. probably not totally
necessary though

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
