### ISSUE TITLE
Keyword search is not functional

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#666]
1. Enter text into the search input.
2. Click the "check/finish" button or press Enter to close the keyboard.
3. Note that your entered text has now been cleared from the search input.

**Comment by mdconatser** [comment]
tested on android

**Comment by Minyahil40** [comment]
tested on iPhone

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
