### ISSUE TITLE
Bug with searching Gmail

### ISSUE THREAD

**Issue by JesterSe7en** [umgc/fall2022#671]
Pre-condition: Use must have Informed Delivery emails in their Gmail account

Environment: Android

Steps to Reproduce:

1.  Log into Google
2. Select Mail Search
3. Select a date range
4. Hit search

Exception thrown @ MailPieceService.fetchMail -> searchMailPieces

**Comment by tatikozh** [comment]
On iOS runtime error as soon as logged in with flutter message "Unable to retrieve email."

**Comment by JesterSe7en** [comment]
@tatikozh That might be different from what I am experiencing.   Can you file a separate issue for this?

**Comment by tatikozh** [comment]
I will, just wanted to mention it because I think it also related to mail fetching
