### ISSUE TITLE
Runtime error when logging in with Gmail account on iOS

### ISSUE THREAD

**Issue by tatikozh** [umgc/fall2022#674]
1. Login using Gmail sign in
2. Runtime error can be observed in the console

![Image](https://user-images.githubusercontent.com/35759841/197620087-c9f12a6a-399f-4692-be61-60d7d8cd2cb6.png)

**Comment by tatikozh** [comment]
For me, the error is still there and no mail is retrieved.
I tried cleaning everything by running "flutter pub cache clean", "flutter clean", "pod cache clean --all", and even "pod
 deintegrate". Set everything up all over again. No luck.

**Comment by Minyahil40** [comment]
I'm not seeing this runtime errors from my side.

**Comment by tatikozh** [comment]
Are you able to see mail or digest from your Gmail account?
I just checked and still have this error in my Xcode console. I can log in but no mail can be seen and I get an error trying to get digest.
