### ISSUE TITLE
Reordering Sign In Layout

### ISSUE THREAD

**Issue by JesterSe7en** [umgc/fall2022#676]
Proposal to reorder the Sign In for slightly better UX.

In relation to https://github.com/umgc/fall2022/issues/652

 
![Screenshot_20221024-131521_USPS Visual Assistance App](https://user-images.githubusercontent.com/5118389/197620645-77862560-6b60-491a-b805-97106e029cd1.png)

**Comment by JesterSe7en** [comment]
Tagging @mdconatser for feedback.

**Comment by mdconatser** [comment]
definitely agree

**Comment by mdconatser** [comment]
or maybe it actually makes more sense above or below "RETRIEVE MAIL" since they have to click the checkbox first

**Comment by JesterSe7en** [comment]
> or maybe it actually makes more sense above or below "RETRIEVE MAIL" since they have to click the checkbox first

I want to keep the google sign in with the user/pass fields to indicate to the user Google sign is an option.  (User can do either one)

I'll push my changes.

**Comment by mdconatser** [comment]
sounds good
