### ISSUE TITLE
Accessibility issue with login screen

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#681]
Occurs when using Android TalkBack

Login screen: recognized terms and conditions not the privacy policy within the text box

**Comment by sims-007** [comment]
Some additional clarification - when the reader gets to the terms and condition box it doesn't read/recognize the privacy policy words in the box. It only states terms and conditions and then ends.

**Comment by tatikozh** [comment]
@sims-007 The new app version has a potential fix. Please, verify if you can.

**Comment by sims-007** [comment]
It now reads each line as its own text box, no longer one box. 
I think it will work since everything is technically read.

**Comment by sims-007** [comment]
Test on Android complete

**Comment by wpbear1742** [comment]
Verified - Test PASS
