### ISSUE TITLE
Accessibility issue with chatbot

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#683]
Encountered using Android TalkBack

When selecting help on the chat box the dialog is broken into two text boxes. Breaks after extra command and also doesn’t read “options.digest” and skips to the next word help, home, etc.

**Comment by sims-007** [comment]
Let me know if this helps: the reader sees this as two text boxes and skips options.digest and picks-up at help.

![SS_App](https://user-images.githubusercontent.com/111534966/198055334-a175a1be-4ca2-4999-bd9e-90c81cc1b884.PNG)

**Comment by mdconatser** [comment]
that looks like just an overall bug, i dont think the last section was meant to be there since it is repeated. I can't get this to happen on the latest version

**Comment by mdconatser** [comment]
@sims-007 can you reproduce this still on the latest version? @shaneknows does this seem like something you fixed earlier?

**Comment by sims-007** [comment]
It's fixed, thanks

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
