### ISSUE TITLE
Long sender names in the search results cause the date to be formatted wrong

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#695]
Long sender names should probably just get wrapped onto the next line so they don't overlap with the date.

![Image](https://user-images.githubusercontent.com/3463782/198076334-e944d342-f6c1-4a3c-9b5a-9d9cfea0b354.png)

**Comment by Minyahil40** [comment]
new formatted view

![Image](https://user-images.githubusercontent.com/111590407/198147344-125b1332-09f1-4621-821c-bea20f930f31.png)

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad

**Comment by wpbear1742** [comment]
Verified - Test PASS
