### ISSUE TITLE
Chatbot keyword search bug

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#704]
- can't seem to get the keyword to work from the chatbot, but it's possible I'm doing it wrong. I tried stuff like "search 10/23/2022 10/25/2022 subaru" and "search subaru" and neither worked
- I think the user would expect that this would also just submit the search to view a list of results, but we can keep it as-is at this point unless that seems easy to implement.

**Comment by lwvantassel** [comment]
keyword search defaults to current day. this should have no date filter applied when searching by keyword only

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad
