### ISSUE TITLE
Optimize the cache process at login

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#726]
Optimize the cache process at login so that it takes less time. Some potential areas for improvement:

- Investigate if any completely "extra" steps are happening that can just be removed (is address detection happening twice?)
- Investigate/develop async improvements to retrieving emails from enough_mail
- Investigate/develop async improvements to sending images to Google Cloud Vision

**Comment by mdconatser** [comment]
tested on android

**Comment by tatikozh** [comment]
tested on iPad, the loading time is notably reduced
