### ISSUE TITLE
Refine Requirement: Open resulting email from search

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#8]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

https://github.com/umgc/fall2022/issues/34 will help with this if completed, alternatively you can run the app on your own.

**Comment by umgcjack** [comment]
This is directly tied to the [search requirement](https://github.com/umgc/fall2022/issues/17) for Team B.
This can be revised based on customer feedback, but likely will revolve around opening the same view that the "Latest" and "Unread" buttons open, but scoped to the results of the search list.

Example of the current view:
![image](https://user-images.githubusercontent.com/111916720/187087308-d86861a3-3963-423b-ab7c-e4b9e39d92ed.png)

**Comment by umgcjack** [comment]
Based on the customer feedback:

- Clicking on an email in the Search Results view shall open the Detailed Email view.
- The Search Results view shall not display all detailed information about an email (limited to a single line)
- The Detailed Email view shall use the existing Next/Previous buttons, but shall navigate to the next and previous emails in the Search Results list.
- There shall be a Back button that returns the user to the Search Results view.
- There shall be a Back gesture that returns the user to the Search Results view.
