### ISSUE TITLE
Refine Requirement: Call, email, or send text message to sender or contact on command

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#9]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

https://github.com/umgc/fall2022/issues/34 will help with this if completed, alternatively you can run the app on your own.

Recommend thinking of what exactly this requirement implies our application needs to implement as individual features. This would start with making sure that the current application doesn't already have these abilities. 

If not, a breakdown would might include questions like: 
- "Is the customer wanting this functionality within a single mail message, as some other sort of "contact" user interface, or both?"
- "Is the customer wanting clickable "links" in the email messages, or an extra UI panel above the message containing any email addresses or phone numbers found?"

Regardless of the answer, both alternatives can be thought about in advance in regards to what our derived requirements are. Stuff like:

- User can click an email address within the body of an email to launch their device's email application's new message view to that recipient
- User can click a phone number within the body of an email to launch their device's phone application with that number to call
- System displays a Contact Panel as a part of the Mail View UI
- System displays links for all email addresses found within the message in the Contact Panel
- System displays links for all phone numbers found within the message in the Contact Panel
- User can click an email address in the Contact Panel to launch their device's email application's new message view to that recipient
- User can click a phone number in the Contact Panel to launch their device's phone application with that number to call

**Comment by kuku-prog** [comment]
The current application doesn't have these abilities. Checked both document and App.

Q: Customer wants these options present in both click based and audio command?(Do we have to consider features for the visually impaired in these project or not?)
